### ISSUE TITLE
Digital potentiometer configuration

### ISSUE THREAD

**Issue by sebprince** [dunewires/ElectricalMethod#11]
The digipots cannot be configured. This requires changes in both firmware and DAQ.

There are 8 digipots, each with an 8-bit configuration value. We would need a 64-bit number, so it would have to be divided into four keys of 16-bit numbers in the header, or three keys of 24 bits.

**Comment by jbattat** [comment]
The digipot setting is now configurable -- @sebprince have you tested this feature to the point where we can close the issue?

**Comment by sebprince** [comment]
The configuration works but when I tested last time there was a mixup in the ordering of the digipots sent in the UDP header relative to what we expected. @alacrities needed to make a change as I understand. I don't know if this change has been done, and if so, which branch to test.

**Comment by sebprince** [comment]
I checked and indeed there's a mixup in the mapping in `dwaTools.py`.

@jbattat All config values and registers associate the least significant channels/wires to the LSB of their parameter, but the digipot config value is opposite. To have coherence, could you swap the order in the file above?
So going from what we have now:
`digipot = 0001020304050607`
to
`digipot = 0706050403020100`

**Comment by jbattat** [comment]
Sure -- I've changed the convention to match the one you suggest (LSB of the digipot config string corresponds to digipot number zero).

```
$ git push
...
To https://github.com/dunewires/ElectricalMethod.git
   c09204d..485e747  dev_gui -> dev_gui
```

**Comment by sebprince** [comment]
The software has been fixed in development branch such that the digipot config parameter now has channel 7 at the left and channel 0 at the right as in `digipot = 0706050403020100`. This association has been check by changing each digipot individually and checking the result in the amplitude vs frequency plots.

The ordering reported in the run frame has also been changed to:
```
30 # digipot setting for gain adjustment ADC channels 7 and 6
31 # digipot setting for gain adjustment ADC channels 5 and 4
32 # digipot setting for gain adjustment ADC channels 3 and 2
33 # digipot setting for gain adjustment ADC channels 1 and 0
```

Closing.
