### ISSUE TITLE
Add delay time before run start

### ISSUE THREAD

**Issue by sebprince** [dunewires/ElectricalMethod#16]
When the instrument is idle, the DC and AC takes some time to ramp up. The firmware does not wait for that currently and start taking data right away. This implies that, for the first few scanned frequencies, a sine wave of increasing amplitude is measured, and is thus useless.

A delay time of a few seconds between the setup and start of the frequency sweep should be added and be configurable.

**Comment by sebprince** [comment]
I attach a screenshot of the issue.
<img width="403" alt="image" src="https://user-images.githubusercontent.com/44129829/112057291-77871f80-8b2f-11eb-8ece-bf5154a43a34.png">

This happens even for subsequent scans after the instrument first scan after power up. The AC signal does turn off between scans.

**Comment by jbattat** [comment]
Has this been confirmed yet (does stimTimeInitial work as expected)?

**Comment by sebprince** [comment]
This seems to be happening again based on quick tests. Reopening to make sure this is properly fixed. Possibly simply increasing the initial stimulus time could solve this in any case.

**Comment by sebprince** [comment]
The new issue is in fact different and cannot be resolved by an initial delay time.
It is being tracked at #98.

Closing this one again.
