### ISSUE TITLE
Actual value of stimFreqMin, Max, Step is 1/2 of the requested value

### ISSUE THREAD

**Issue by jbattat** [dunewires/ElectricalMethod#18]
In the python daq config file, if user requests:
```  
  22000148 —> stimFreqMin  = 0x148 = 328d = 20.5 Hz
  23000280 —> stimFreqMax  = 0x280 = 640d = 40.0 Hz
  24000002 —> stimFreqStep = 0x002 =   2d = 1/8Hz = 0.125 Hz.
```
the actual frequency scan runs from 10-20Hz with a step size of 1/16 Hz (not 1/8 Hz).

So actual frequencies (min, max, step) are factor of 2 smaller than requested ones.

**Comment by alacrities** [comment]
This is fixed but not tested in 
https://github.com/dunewires/ElectricalMethod/pull/new/fix/nfelt/freqDiv-stimUnits
there is an updated boot.bin with the ADC emulator off to be run on the DWA.

**Comment by sebprince** [comment]
Tested with v4_0 and this is indeed fixed. Closing this issue.
