### ISSUE TITLE
anomalous final reported frequency in a scan

### ISSUE THREAD

**Issue by jbattat** [dunewires/ElectricalMethod#19]
In a scan, the final frequency, as reported in the frequency header, is anomalous. 
The actual frequency is likely OK (based on amplitude vs. frequency plots) -- @sebprince can you confirm that your plots of amplitude vs. frequency included all 158 frequencies (especially the final one)?
But the reported frequency for the final iteration is anomalous.  See final black point in graph below.
![20200813T000904_freqAndSamplingPeriod](https://user-images.githubusercontent.com/8468957/90799827-c6db4800-e2e1-11ea-9e9c-25933ef7b6f8.png)

**Comment by sebprince** [comment]
I plotted the raw data for channel 0 by decreasing order of frequency (including the values in the subplot titles). I got the plot attached. This seems to have an amplitude higher than frequencies near the beginning of the range. This confirms the amplitude plotted in the overall amplitude vs frequency plot, which I'm also attaching.

So the actual frequency that was run seems to be correct. This points towards a bug only in the reported value of the frequency.

[lastfreqschannel0.pdf](https://github.com/dunewires/ElectricalMethod/files/5105594/lastfreqschannel0.pdf)
[allchannels.pdf](https://github.com/dunewires/ElectricalMethod/files/5105599/allchannels.pdf)

**Comment by sebprince** [comment]
This is still an issue in v4_0. However, as can be seen in attached plot, the last frequency value is now a repeat of the previous one (but the amplitude corresponds to a larger frequency). This seems to be an issue in the labelling of the frequency and I suspect it is related to #43.

![allchannels](https://user-images.githubusercontent.com/44129829/108239066-82592980-7117-11eb-8437-a8f5caa7f81f.png)

**Comment by alacrities** [comment]
This is fixed in the development branch.  Ned to verify with a frequency scan.

**Comment by sebprince** [comment]
It is indeed fixed. Closing this issue.
