### ISSUE TITLE
Changing stimTime does nothing

### ISSUE THREAD

**Issue by sebprince** [dunewires/ElectricalMethod#21]
It seems that the stimulus time configuration parameter does not behave as expected.

I tried two runs, from 10 Hz to 20 Hz with 1/16 Hz step and with 8 cycles, one using
`stimTime           = 00000010`
and one using
`stimTime           = 10000000`

Both runs took 1min50s to complete. I would have expected the first one to be near instantaneous and the second one to be overly long.

**Comment by alacrities** [comment]
the stimTime is a 24 bit signal so the MSB will be ignored.  THis should be reflected in the header.  Not sure why the run takes so long.  We should check the header to see what value is being set.  
There is a new branch that changes the units of the stimTime to 2.56us with updated boot.bin
https://github.com/dunewires/ElectricalMethod/pull/new/fix/nfelt/freqDiv-stimUnits

**Comment by sebprince** [comment]
I tested this with v4_0. I tried both
`stimTime = 10000000`
and
`stimTime = 00000000`.
Both resulted in a very short run of perceptively the same duration. So this indeed seems to indicate that the MSB is not considered properly. The run header shows `2C000000` for both, as it is expected. Closing this issue.
