### ISSUE TITLE
Eliminate defunct 2-line UDP header

### ISSUE THREAD

**Issue by jbattat** [dunewires/ElectricalMethod#4]
The new headers format has a UDP frame ("AAAA"). We should get rid of the old 2-line UDP header -- the one that looked like this:
```
F0000175
00000018
```

**Comment by sebprince** [comment]
Tested in v4_0 and I didn't see this data format used anywhere. Closing this issue.

**Comment by jbattat** [comment]
you won’t see that data in the files because the python daq senses/cuts those lines.  Are you sure that those lines are not in the raw UDP stream?

**Comment by sebprince** [comment]
This is a good point. I did not check in the raw UDP stream as I'm not sure how to do this, see #5 for a related discussion.

**Comment by jbattat** [comment]
The raw udp stream is logged (appended) to udpstream.txt in the same directory as dwaDaq.py.  You can look at that file to see if the defunct header still exists. Recommend first deleting that file (manually) before starting a scan and then looking at the first two lines of the newly created udpstream.txt file after a scan has begun.

**Comment by sebprince** [comment]
I looked at the raw UDP data and I confirm that this issue is still relevant in v4_0.

**Comment by jbattat** [comment]
in the version that is currently on the uzed in my lab, this is no longer an issue (Nathan has removed the two defunct UDP header lines). Can likely close this issue

**Comment by sebprince** [comment]
Yes, looking at `udpstream.txt ` I don't see these headers. Closing this issue.
