### ISSUE TITLE
DAQ does not remove previous-scan peak location lines

### ISSUE THREAD

**Issue by sebprince** [dunewires/ElectricalMethod#41]
Using v4_0, I noticed that when performing a new scan after a first one has fully completed, including peak finding and display of their locations, the red lines used to display the peak locations of the first scan are not erased. See attached screenshot taken in the middle of the second scan. Since the red lines are not cleared, this has as consequence that the scale of the x-axis is also not reset.

These red lines should be removed when the data points are removed, after starting a new scan.
<img width="1428" alt="Screen Shot 2021-02-16 at 7 38 35 PM" src="https://user-images.githubusercontent.com/44129829/108167389-9bd08600-70c3-11eb-9d6f-c38736c0a5f6.png">

**Comment by jbattat** [comment]
resolved in current version (dev_gui branch)
