### ISSUE TITLE
First scan frequency is skipped

### ISSUE THREAD

**Issue by sebprince** [dunewires/ElectricalMethod#43]
Using v4_0, doing a frequency scan from 70 Hz to 80 Hz with a frequency step of 1 Hz, the first data received by UDP is 71 Hz. However, measuring with a scope, 70 Hz is the start frequency as it should. Based on the scope, the UDP data for 71 Hz appears right after transitioning to 71 Hz. Since there's stimulus time, which should occur after transitioning to a new frequency and before digitizing the signal, this seems to indicate an off-by-1 incorrect association between frequency labelling and actual frequency. In other words, the information in UDP data associated to 71 Hz was really collected by using 70 Hz. The sampling time received by UDP associated to the 71 Hz is consistent with 71 Hz.

Also, using a fixed frequency instead of a frequency scan, the frequency information received by UDP matches the requested frequency and also matches what is measured with a scope.

So it seems that there's an issue in the labelling of the frequency only when doing a frequency scan. Possibly, there could be an issue in how the frequency step labels are calculated when segmenting the overall requested frequency range.

**Comment by alacrities** [comment]
This is fixed in the development branch. Need to verify with the DAQ.

**Comment by sebprince** [comment]
It is fixed. Closing this issue.
