### ISSUE TITLE
Wrong end frequency in scan

### ISSUE THREAD

**Issue by sebprince** [dunewires/ElectricalMethod#44]
Using v4_0, doing a frequency scan from 70 Hz to 90 Hz with a frequency step of 1/16 Hz, the last frequency does not match the requested frequency, while it should since it can be evenly divided. See attached plot (never mind having two data points for the last frequency, which is probably a separated issue cf. #19 and #43).

From the received UDP data, the number of periods for the second-to-last frequency is `0x10F630`, corresponding to 89.96041741633681, and the number of periods for the last frequency is `0x10F310`, corresponding to 90.02520705797623.

However, this last frequency is fine if the scan is from 70 Hz to 80 Hz: `0x1312D0` corresponding to 80.0.

The cause of this is not clear to me. Possibly, this could be related to a lack of precision specific to the overall requested frequency range, or due to a lack of precision accumulating (larger ranges have more imprecision).
![allchannels](https://user-images.githubusercontent.com/44129829/108276447-d5e26c00-7145-11eb-82c1-9869da600f48.png)

**Comment by alacrities** [comment]
This is fixed in the development branch. Need to verify with the DAQ.

**Comment by sebprince** [comment]
Confirmed fixed. Closing this issue.
