### ISSUE TITLE
Digipots not using configuration values

### ISSUE THREAD

**Issue by sebprince** [dunewires/ElectricalMethod#45]
In v4_0, while using the system I stumbled on two separate occasions upon the digipot settings not being set to the values specified in the configuration file. They were all set to their lowest values of `00`. Looking at the run header shows that the correct values are displayed:
```
30000000
31000000
32000000
33000000
```
But the signal was saturating, a symptom that the digipots were set at a very high configuration value. Setting the values anew did not change the gain, presumably because the firmware thought it was already set at this value. Indeed, setting to a slightly different value, `01`, reduced the gain as expected.

This issue possibly is triggered by an ssh disconnect to the laptop running the DAQ, closing it. This unexpected close seems to affect the hardware communication to the digipots.

**Comment by alacrities** [comment]
I can change the logic to update the digipot for every register write, not just a different value being written.  I am just unclear on how the first time this value was written to the register, it didn't update the digipot.  Was there some voltage "event" on the analog board that caused the digipot to loose power and not the DWA?

**Comment by sebprince** [comment]
I don't recall the manipulation details. Possibly it happened after I was probing the pins of digipots and I could have touched DI and VCC together (pins 2 and 3)... That might explain it. I'll close this issue as it's hardly reproducible anyway.
