### ISSUE TITLE
DAQ speed limiting

### ISSUE THREAD

**Issue by sebprince** [dunewires/ElectricalMethod#47]
In v4_0, when doing a frequency scan without stimulus time, the scan finishes quickly but it takes longer to have the run done since the DAQ needs to process and display all that data. I'm not sure where the limitation comes from, maybe the refresh rate of the GUI? This might not be a problem per se, but if we ever go with decreasing the stimulus time to make the measurement faster, then the DAQ becomes a speed limitation of the measurement process.

**Comment by jbattat** [comment]
closing -- related to #40
