### ISSUE TITLE
DAQ: Plot transform "Log X" 

### ISSUE THREAD

**Issue by sebprince** [dunewires/ElectricalMethod#48]
In v4_0, performing a plot transform by right clicking and choosing "Plot Options" -> "Transforms" -> "Log X" does not transform the red bars (showing the peak locations) correctly, as can be seen in the attached screenshot. The data points get transformed correctly.
This might have been fixed in a newer version of the DAQ if related to #41.
<img width="398" alt="image" src="https://user-images.githubusercontent.com/44129829/108936468-688a7b80-761c-11eb-91f7-7a02ed897751.png">

**Comment by sebprince** [comment]
I confirm this happens in the latest commit of `dev_gui`, 931d379.

**Comment by jbattat** [comment]
this is a known issue in pyqtgraph:
https://github.com/pyqtgraph/pyqtgraph/issues/22
