### ISSUE TITLE
Frequency step varying during scan

### ISSUE THREAD

**Issue by sebprince** [dunewires/ElectricalMethod#49]
In v4_0, during a scan from 70 to 90 Hz with a step of 1/16 Hz, some uneven step sizes are observed, as in the attached screenshot. It's unclear to me what could be the cause of this. It might be related to #46.

<img width="363" alt="image" src="https://user-images.githubusercontent.com/44129829/109220485-f8e4cf80-7786-11eb-8b43-e793ab0c9c26.png">

**Comment by alacrities** [comment]
This is fixed in the development branch. Need to verify with the DAQ.

**Comment by sebprince** [comment]
Repeating the same test with the new version, I didn't see that behaviour. Closing this issue.
