### ISSUE TITLE
Scan stops after end frequency

### ISSUE THREAD

**Issue by sebprince** [dunewires/ElectricalMethod#51]
With the latest firmware (with end run frame), the frequency scans stop after the specified max frequency.
See attached screenshot, with the max frequency listed on the left sidebar as specified in the config file but with the data points extending beyond that. The frequency frame in the UDP data does contain that larger-than-max frequency value.
<img width="1412" alt="Screen Shot 2021-04-14 at 10 32 44 PM" src="https://user-images.githubusercontent.com/44129829/114806172-4981ad80-9d72-11eb-8793-fd729550338d.png">

**Comment by alacrities** [comment]
when using the dev gui and development firmware the scan is stopping at the max frequency.  The plot disappears when the scan finishes but the last active frequency is the max frequency. 
![Screenshot from 2021-04-21 20-45-47](https://user-images.githubusercontent.com/15349780/115639604-0af47180-a2e3-11eb-9a52-f4dd27220787.png)

**Comment by sebprince** [comment]
This is now fixed in the development branch.
Closing.
