### ISSUE TITLE
Accurate amplitude fitting

### ISSUE THREAD

**Issue by sebprince** [dunewires/ElectricalMethod#55]
There are some concerns that the amplitude fit of the raw ADC data is not working appropriately based on looking in the GUI at the quickly appearing/disappearing ADC data as a function of time during a scan. The fit could possibly only be performed for channel 0, with the other channels only displaying a duplicated channel 0 fit regardless of their data.

For some scans and frequencies, and for different channels, the accuracy of the fits obtained during a scan should be investigated by comparing them to fits obtained by manually plotting and fitting the raw data.

**Comment by jbattat** [comment]
I have checked this with the new "event viewer" capability. I have not see any fitting issues. Closing for now, but if someone notices an issue in the future, please reopen and post the problematic data so that I can test.
