### ISSUE TITLE
AttributeError in post scan analysis

### ISSUE THREAD

**Issue by sebprince** [dunewires/ElectricalMethod#56]
This error appears for some scans at the end of them:
```
postScanAnalysis():
detrending
detrending
detrending
detrending
detrending
detrending
detrending
detrending
Clearing fit lines from the resonance plots
in update: 0: [321.06439267459484, 322.6889020832796, 323.7524200493399, 331.4397078027536, 337.75111795620046]
Chan, Freq = 0, 0, 321.06439267459484
ymin, ymax = 8.600109065595348, 20.929567243001202

Traceback (most recent call last):
  File "/Users/sprince/DUNE/ElectricalMethod/DAQ/python/dwaDaq.py", line 1483, in processUdpPayload
    self.postScanAnalysis()
  File "/Users/sprince/DUNE/ElectricalMethod/DAQ/python/dwaDaq.py", line 1602, in postScanAnalysis
    self._updateResonantFreqDisplay(chan=None)
  File "/Users/sprince/DUNE/ElectricalMethod/DAQ/python/dwaDaq.py", line 1654, in _updateResonantFreqDisplay
    self.resFitLines['proc'][reg][-1].sigClicked.connect(self._f0LineClicked)
AttributeError: 'InfiniteLine' object has no attribute 'sigClicked'
```
It seems that the issue with the software, not with the data, so it should be fixed.

Here is example data that triggers the error, and a screenshot of it: [data_320-340Hz_noisy.zip](https://github.com/dunewires/ElectricalMethod/files/6603278/data_320-340Hz_noisy.zip)
<img width="1428" alt="mid freq no sawtooth" src="https://user-images.githubusercontent.com/44129829/120906341-aee17480-c626-11eb-8e33-5be945308aa7.png">

**Comment by jbattat** [comment]
This error arises because the DAQ uses a feature of InfiniteLine that was
recently added to pyqtgraph. If you update the pyqtgraph installation, the
error should go away:

  $ pip install pyqtgraph --upgrade

Let me know if the error persists (it should not).

James

**Comment by sebprince** [comment]
That did it!
Closing this issue.
