### ISSUE TITLE
Missing end run frame

### ISSUE THREAD

**Issue by sebprince** [dunewires/ElectricalMethod#61]
Since missing UDP packets occur, see #40, the end run frame sometimes goes missing. Since this frame is critical for the proper working of the DAQ, it it goes missing it requires a restart of the DAQ. Solving the aforementioned issue would fix having to restart the DAQ, but here are two avenues to solve this particular situation:

1. Allow to start a run without having received the end run frame, by not disabling the "Start run" button after the start of a run
2. Receive run frames, both start and end, by TCP. The start run frame could be fetched when the TCP configuration is done and the end run frame could be fetched when the status frame reports a return to idle state. This approach is related to the implementation in #57.

**Comment by jbattat** [comment]
We should have a discussion about this. One of the goals of the STATUS frame was to provide the DAQ with actionable information. e.g. if the uzed reports that it is in the IDLE state, then the DAQ knows that it is safe to start a scan (and also that the old scan is done). But we are currently not guaranteed that the uzed will be sending status frames, so the DAQ cannot rely on that information. The DAQ development would benefit from some clarification on what information will be reliably available. The loss of UDP packets (and how to handle them) is another important discussion element. Perhaps all communication should be done via TCP/IP, for example.

**Comment by chrisstanford** [comment]
Doesn't the uzed send a IDLE state via the heartbeat? If one of these packets gets dropped, won't it be reported in the next heartbeat?

**Comment by jbattat** [comment]
Yes, but the STATUS (heartbeat) can be disabled entirely.

**Comment by sebprince** [comment]
If we can fix #40, then this issue here is moot.

Regarding TCP communication for all packets, I don't think right now we have any TCP communication initiated by the microzed. I'm not sure how that would be implemented, but it possibly could be done. However, I'm afraid it would create delays in receiving data, similar to how there's delays to configure the firmware. From what I remember that was the motivation to go with UDP in the first place.

I think we should try solving #40, and if we cannot or it's not a reliable solution, then we can try solving this issue specifically.

**Comment by jbattat** [comment]
Since issue #40 is fixed, closing this one...
