### ISSUE TITLE
GUI in Windows launches outside the screen

### ISSUE THREAD

**Issue by sebprince** [dunewires/ElectricalMethod#67]
When starting the GUI on Windows on a laptop with a screen resolution of 1366x768, the window is outside the screen, see attached screenshot. This is especially bad since the window's title bar itself is outside the screen meaning it cannot be closed by the red X button or be dragged more inside the screen. The screen can be resized by the border though and that prompts the OS to reposition the window fully inside the screen.

The launch position and dimensions of the GUI window should be fixed to be fully within the screen, possibly with the window maximized (at least on Windows).
![Screenshot 2021-07-08 180607](https://user-images.githubusercontent.com/44129829/124996875-b7f3a600-e017-11eb-92f7-ae92719710ed.png)

**Comment by jbattat** [comment]
fixed: GUI opens in maximized mode on windows now (could have this be the default on all platforms...)
