### ISSUE TITLE
End-of-scan indicator

### ISSUE THREAD

**Issue by jbattat** [dunewires/ElectricalMethod#9]
The python DAQ listens/receives data from a scan. It would be helpful for it to get positive confirmation from the uzed that the scan is finished. This could either by via transmission of an "end of scan" header, such as:
```
FFFF0001
99000000
FFFFFFFF
```
or via the Status register sending a "scan finished" signal.

**Comment by alacrities** [comment]
This is fixed in the feature/nfelt-busy-status-in-run-heade. Need to verify with the DAQ.

**Comment by jbattat** [comment]
The DAQ sees/handles end-of-scan indicator
