### ISSUE TITLE
Step size in single-segment scan

### ISSUE THREAD

**Issue by sebprince** [dunewires/ElectricalMethod#94]
The step size listed in the configuration table is not honoured when doing a single-segment scan.
This issue prompts the question whether we want to keep having the ability to do single-segment scans given that all scans in a layer are now the same. The single-segment scan feature could be considered to be removed.

**Comment by chrisstanford** [comment]
I am in favor of removal. It is rather quick to just redo the scan of 8 channels that contains the desired wire

**Comment by sebprince** [comment]
That's what I'm thinking too. Also, doing a scan of 8 wires does not mean updating the tension for all 8 wires if the tension for the other 7 is deleted from the entry boxes before submitting to DB. As I understand, only non-empty values would be overwritten in the DB.

**Comment by sebprince** [comment]
It's not clear if the new results table would allow for only a subset of channels to be considered as being the final result.

**Comment by sebprince** [comment]
The single-segment functionality has been removed. Issue #97 has been created to address the previous comment in a more general way.

Therefore, the current issue can be closed.
